In [1]:
import numpy as np

In [2]:
X = np.random.rand(100, 1)

In [4]:
X[1]

array([0.74364673])

In [11]:
Y = 2 + (3 * X) + np.random.randn(100, 1)

In [12]:
Y[1]

array([3.66966211])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])